In [ ]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [ ]:
env = gym.make("FrozenLake-v1")

In [ ]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

print(action_space_size)
print(state_space_size)

4
16


In [ ]:
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#total number of episodes we want agent to play for training
num_episodes = 10000
#max steps agent can take before termination
max_steps_per_episode = 100


learning_rate = 0.1 #alpha
discount_rate = 0.92 #gamma

# handles a balance between exploration and exploitation
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
#track scores 
rewards_all_episodes = []


#Q-Learning Algorithm

for episode in range(num_episodes):
  state = env.reset()

  done = False # tracks whether episode finished or not
  rewards_current_episode = 0 

  for step in range(max_steps_per_episode):
    # Exploration-exploitation trade off
    exploration_rate_threshold = random.uniform(0, 1)
    if exploration_rate_threshold > exploration_rate:
      action = np.argmax(q_table[state,:])   # exploit the environment and chooses action with highest q-value at this state
    else:
      action = env.action_space.sample() # agent will explore the environment. sample an action randomly.
    
    new_state, reward, done, info = env.step(action)    

    #Update Q-Table for Q(s,a)
    q_table[state, action] = q_table[state,action] * (1 - learning_rate) + \
       learning_rate * ( reward + discount_rate * np.max(q_table[new_state, :]))
    
    state = new_state
    rewards_current_episode += reward

    if done == True:
      break
    
  #Exploration Rate Decay
  exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
  
  rewards_all_episodes.append(rewards_current_episode)

In [ ]:
# Calculate and print the average reward per thousand episodes

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("Average Rewards per thousand episodes \n")
for r in rewards_per_thousand_episodes:
  print(count, ":", str(sum(r/1000)))
  count += 1000

#Print updated q-table

print("\n Q-Table \n")
print(q_table)

Average Rewards per thousand episodes 

1000 : 0.03100000000000002
2000 : 0.16800000000000012
3000 : 0.3110000000000002
4000 : 0.3940000000000003
5000 : 0.4240000000000003
6000 : 0.5520000000000004
7000 : 0.4850000000000004
8000 : 0.5370000000000004
9000 : 0.5440000000000004
10000 : 0.5180000000000003

 Q-Table 

[[0.05247629 0.05531855 0.0590736  0.05262206]
 [0.04619486 0.04541249 0.04956274 0.05550541]
 [0.05987857 0.06533467 0.05937194 0.05983874]
 [0.04225558 0.03678994 0.03375975 0.05289591]
 [0.07592051 0.06264567 0.05931405 0.05777355]
 [0.         0.         0.         0.        ]
 [0.1032314  0.06691335 0.05197833 0.02135513]
 [0.         0.         0.         0.        ]
 [0.08479011 0.08666076 0.09641203 0.11992831]
 [0.16859413 0.19581029 0.17326242 0.16737243]
 [0.24491709 0.1945606  0.17958997 0.11528884]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.22258662 0.24362088 0.32690583 0.26202922]
 [0.44012138 0.43255135 0.4

In [ ]:
# for episode in range(3):
#   state = env.reset()
#   done = False
#   print("* EPISODE", episode+1, "*******\n")
#   time.sleep(1)

#   for step in range(max_steps_per_episode):
#     clear_output(wait=True)
#     env.render()
#     time.sleep(0.3)

#     action = np.argmax(q_table[state,:])
#     new_state, reward, done, info = env.step(action)

#     if done:
#       clear_output(wait=True)
#       env.render()
#       if reward == 1:
#         print("Reached goal !")
#         time.sleep(3)
#       else:
#         print("Fell through a hole")
#         time.sleep(3)
#       clear_output(wait=True)
#       break

#       state = new_satate
# env.close()
